const AUTH = {
  LOG_IN_SUCCESSFUL: "LOG_IN_SUCCESSFUL",
  NOT_LOGGED_IN: "NOT_LOGGED_IN",
  LOG_OUT: "LOG_OUT",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  GET_PROJECT_DATA: "GET_PROJECT_DATA"
}

export default AUTH
