const AUTH = {
  LOG_IN_SUCCESSFUL: "LOG_IN_SUCCESSFUL",
  NOT_LOGGED_IN: "NOT_LOGGED_IN",
  LOG_OUT: "LOG_OUT",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  UPDATE_PROJECT_NAMES: "UPDATE_PROJECT_NAMES"
}

export default AUTH
