const VISUALISE = {
  UPDATE_SCREEN_DIMENSIONS: "UPDATE_SCREEN_DIMENSIONS",
  OPEN_PERSON: "OPEN_PERSON",
  OPEN_SKILL: "OPEN_SKILL",
  CLOSE_FULL_DETAILS: "CLOSE_FULL_DETAILS",
  TOGGLE_FULL_DETAILS: "TOGGLE_FULL_DETAILS",
  TOGGLE_FILTER: "TOGGLE_FILTER",
  TOGGLE_SELECT_ALL_FILTER: "TOGGLE_SELECT_ALL_FILTER",
  CHANGE_MIN_CONNECTIONS: "CHANGE_MIN_CONNECTIONS",
  SUB_GROUP_SELECT: "SUB_GROUP_SELECT",
  CHANGE_DIMENSION: "CHANGE_DIMENSION",
  FETCH_SKILL_NETWORK_DATA_FAILURE: "FETCH_SKILL_NETWORK_DATA_FAILURE",
  FETCH_SKILL_NETWORK_DATA: "FETCH_SKILL_NETWORK_DATA",
  CHECK_CONNECTION_FILTER: "CHECK_CONNECTION_FILTER",
  UPDATE_NODES_AND_LINKS: "UPDATE_NODES_AND_LINKS"
}

export {VISUALISE}
